### ISSUE TITLE
Необходимо добавить поле: Организация, которая провела регистрацию ДТП

### ISSUE THREAD

**Issue by EliahuGunzhin** [avtocod/specs#12]
Наименование группы филдов | `accidents`

### Добавляемые филды

Ниже перечислены филды, которые необходимо добавить в файл спецификации согласно правилам, описанным в [readme-файле][readme]:

```json
{
    "path": "accidents.history.items[].org.name",
    "description": "История ДТП. Организация, которая провела регистрацию ДТП",
    "types": [
        "string"
    ]
}
```
[readme]:https://github.com/avtocod/specs/blob/master/README.md

**Comment by AleksandrVasiliev** [comment]
Добавили
accidents.history.items[].org.name
в спецификацию
