### ISSUE TITLE
Вынести SDK в отдельный репозиторий

### ISSUE THREAD

**Issue by Reallife** [avtocod/specs#137]
Необходимо разделить данные(спецификации) и `SDK` для работы с этими данными по разным репозиториям. 

Это позволит:
- разделить зоны ответственности репозиториев
- упростить реализацию клиентских интеграций и `SDK` на других языках (`Golang`, `Python` и пр.)
- избавиться от влияния изменений в `SDK` на версионирование данных

Этапы выполнения:

- [x] Вынести `SDK` в отдельный репозиторий
- [x] Написать тесты спецификаций (лучшим вариантом видится использование `nodejs` - большой выбор инструментов, многопоточность, быстрая работа в `GitHub Actions`):
  - [ ] Проверка структуры директорий
  - [ ] Проверка наличия схем для каждого файла спецификаций
  - [ ] Проверка валидности схем
  - [ ] Проверка валидности примеров отчётов
  - [ ] Проверка корректности типов данных для филдов
- [ ] Обновить документацию

**Comment by tarampampam** [comment]
@Reallife wrong milestone for this issue =)

**Comment by tarampampam** [comment]
All is done
