### ISSUE TITLE
Добавление новых статусных полей

### ISSUE THREAD

**Issue by Yuri364** [avtocod/specs#22]
Вопрос                     | Ответ
-------------------------- | :---:
Наименование группы филдов | `accidents`
Наименование группы филдов | `fines`

### Добавляемые филды

```json
{
    "path": "accidents.has_accidents",
    "description": "История ДТП: факт истории ДТП или повреждений из страховых компаний",
    "types": [
        "boolean"
    ]
}
```

```json
{
    "path": "fines.has_fines",
    "description": "Штрафы: есть ли у ТС штрафы",
    "types": [
        "boolean"
    ]
}
```

[readme]:https://github.com/avtocod/specs/blob/master/README.md

**Comment by Belobokovm** [comment]
Описание "accidents.has_accidents"
Будет лучше сделать таким:
"Наличие у ТС ДТП по данным ГИБДД и страховых компаний"

**Comment by Belobokovm** [comment]
Описание для "fines.has_fines"
"Штрафы: Имеет ли данное ТС штрафы?"

**Comment by tarampampam** [comment]
Rdy
