### ISSUE TITLE
Насколько актуален справочник моделей ТС и как часто он обновляется?

### ISSUE THREAD

**Issue by gomzyakov** [avtocod/specs#261]
Не нашел Niva Travel в фильтре моделей на https://profi.avtocod.ru

Насколько актуален справочник моделей ТС и как часто он обновляется?

На том же https://auto.ru/ekaterinburg/cars/vaz/niva-travel/all/ данная модель присутстует.

**Comment by Zaboday** [comment]
- Справочник обновляется один раз в месяц.
- Мы считаем что Niva Travel является поколением модели **Niva**: `Lada (ВАЗ) 
/ Niva / I Рестайлинг (Travel)`.

**Comment by gomzyakov** [comment]
@Zaboday Спасибо!
