### ISSUE TITLE
Добавление спецификаций идентификаторов марок и моделей

### ISSUE THREAD

**Issue by tarampampam** [avtocod/specs#31]
## Описание предлагаемого функционала

Необходимо добавить `json`-файлы, содержащие полный набор всех поддерживаемых уникальных  идентификаторов марок и моделей транспортных средств.

**Comment by Belobokovm** [comment]
Добавлены json-файлы, содержащие полный набор всех поддерживаемых уникальных идентификаторов марок и моделей транспортных средств с грузовыми и мотоциклами?

**Comment by tarampampam** [comment]
https://github.com/avtocod/specs/releases/tag/v2.10.0
