### ISSUE TITLE
Исправление ошибки в спецификации полей

### ISSUE THREAD

**Issue by Belobokovm** [avtocod/specs#37]
@Вопрос                     |  @Ответ
-------------------------- | :---:
Наименование группы филдов | `default`

В спецификации имеется продублированная запись (2 одинаковых записи.):
```json
 {
        "path": "repairs.history.items[].insurer.name",
        "description": "Название страховой компании",
        "types": [
            "string"
        ]
    },
```
Необходимо заменить одну из записей на:
```json
 {
        "path": "repairs.history.items[].assessor.name",
        "description": "Название  компании проводившей оценку",
        "types": [
            "string"
        ]
    },
```
### Добавляемые филды

Ниже перечислены филды, которые необходимо добавить в файл спецификации согласно правилам, описанным в [readme-файле][readme]:

```json
 {
        "path": "repairs.history.items[].assessor.name",
        "description": "Название  компании проводившей оценку",
        "types": [
            "string"
        ]
    },
```

[readme]:https://github.com/avtocod/specs/blob/master/README.md

**Comment by Belobokovm** [comment]
@tarampampam Николай, надо поправить

**Comment by tarampampam** [comment]
PR mergen and soon will be merged with `master` branch
