### ISSUE TITLE
Расширение спецификации поддерживаемых марок и моделей

### ISSUE THREAD

**Issue by DenSul** [avtocod/specs#49]
### Что необходимо
- Необходимо добавить в спецификации марок и моделей, марки и модели которые не относятся к легковому транспорту. Т.е. грузовые, мото, строительную и т.д.
- Необходимо добавить новый филд в спецификации моделей: тип ТС.
- Необходимо добавить спецификацию типов ТС.

**Comment by tarampampam** [comment]
Released: https://github.com/avtocod/specs/releases/tag/v3.4.0
