### ISSUE TITLE
Добавить вероятный признак рег. действия

### ISSUE THREAD

**Issue by Yuri364** [avtocod/specs#61]
Вопрос                     | Ответ
-------------------------- | :---:
Наименование группы филдов | `registration_actions`

### Добавляемые филды

Ниже перечислены филды, которые необходимо добавить в файл спецификации согласно правилам, описанным в [readme-файле][readme]:

```json
{
        "path": "registration_actions.items[].attributes",
        "description": "Вероятный признак рег. действия [LEASING, ANNULMENT]",
        "types": [
            "array"
        ],
        "fillable_by": [
            "base.ext"
        ]
 }
```

[readme]:https://github.com/avtocod/specs/blob/master/README.md

**Comment by tarampampam** [comment]
Released in: https://github.com/avtocod/specs/releases/tag/v3.6.0
