### ISSUE TITLE
Добавить итоговый признак аннулирования рег. действия

### ISSUE THREAD

**Issue by Zaboday** [avtocod/specs#63]
Вопрос                     | Ответ
-------------------------- | :---:
Наименование группы филдов | `registration_actions`

### Добавляемые филды

Ниже перечислены филды, которые необходимо добавить в файл спецификации согласно правилам, описанным в [readme-файле][readme]:

```json
{
        "path": "registration_actions.has_annulment",
        "description": "Регистрационные действия: Признак аннулирования последнего рег. действия",
        "types": [
            "boolean"
        ],
        "fillable_by": [
            "base.ext"
        ]
    }
```
```json
    {
        "path": "registration_actions.items[].usage_allowed",
        "description": "Вероятный признак, возможно ли эксплуатация ТС?",
        "types": [
            "boolean"
        ],
        "fillable_by": [
            "base",
            "base.ext"
        ]
    }
```
[readme]:https://github.com/avtocod/specs/blob/master/README.md

**Comment by tarampampam** [comment]
Released in: https://github.com/avtocod/specs/releases/tag/v3.6.0
