### ISSUE TITLE
Добавить описание полей для группы pledges (тип уведомления и указатель на нахождение в залоге) 

### ISSUE THREAD

**Issue by AleksandrVasiliev** [avtocod/specs#9]
Вопрос                     | Ответ
-------------------------- | :---:
Наименование группы филдов | `pledges`

### Добавляемые филды

Ниже перечислены филды, которые необходимо добавить в файл спецификации согласно правилам, описанным в [readme-файле][readme]:

```json
    {
        "path": "pledges.items[].type",
        "description": "Обременения на ТС: Тип уведомления",
        "types": [
            "string"
        ]
    },
    {
        "path": "pledges.items[].in_pledge",
        "description": "Обременения на ТС: Состояние залога",
        "types": [
            "boolean"
        ]
    },
```

[readme]:https://github.com/avtocod/specs/blob/master/README.md

**Comment by tarampampam** [comment]
Closed: #10
