### ISSUE TITLE
Добавить новое поле в блок mileages

### ISSUE THREAD

**Issue by Yuri364** [avtocod/specs#91]
Вопрос                     | Ответ
-------------------------- | :---:
Наименование группы филдов | `mileages`

### Добавляемые филды

Ниже перечислены филды, которые необходимо добавить в файл спецификации согласно правилам, описанным в [readme-файле][readme]:

```json
{
        "path": "mileages.items[].filled_by.source",
        "description": "Пробеги: Имя источника, от которого получено значение пробега",
        "types": [
            "string"
        ]
 }
```

[readme]:https://github.com/avtocod/specs/blob/master/README.md

**Comment by tarampampam** [comment]
Released: https://github.com/avtocod/specs/releases/tag/v3.15.0
